### ISSUE TITLE
Enable Camera before sh install.sh

### ISSUE THREAD

**Issue by jpbellona** [JacksonCoder/pystreamer-http#3]
Should add in the installation instructions that the camera must be enabled before running $ sh install.sh

This is currently not in instructions, and we had to do this when we installed on a new Pi.

Thanks again for your coding ninja skills on the project Jackson.

**Comment by JacksonCoder** [comment]
No problem! I'll add this right now.

**Comment by JacksonCoder** [comment]
I added all the requested information to the README. I think we can close these issues.
